---
title: Methods for Reliable, Transparent, and Open Science 
author: Jeff Rouder & Joachim Vandekchkhxerqvtszwstcas 
output: html_document
---


# Topics

Week 1: **Overview** (JR)

- *In Class*: Jeff's Talk: "Teaching Open Science," https://osf.io/wu8nq/

- *In Class*: Brene Brown, "The Power of Vulnerability" https://www.ted.com/talks/brene_brown_on_vulnerability 

- *Watch After Class*: Brene Brown, "Why Your Critics Aren't The Ones Who Count" http://99u.com/videos/20052/brene-brown-stop-focusing-on-your-critics

- *Write* (due next week): Reflections on vulnerability and self compassion (This is for you.  You can write as much or as little as you want.  It is your chance to reflect as you wish.  This assignment is not graded; it is not even evaluated.  I am grateful for your consideration.)

Week 2: **What Went Wrong: Learning From Jeff's Mistakes* (JV)

Mistakes. Mistakes.  We review how people fool themselves, and addressing these mistakes motivates much of the rest of the course!

- *Read*:  Brian Wansink, https://www.buzzfeed.com/stephaniemlee/who-really-ate-the-apples-though?utm_term=.nlBadBdW3#.srB59g9L2

- *Read*: Brad Bushman, http://retractionwatch.com/2016/12/09/dispute-shooter-video-games-may-kill-recent-paper/
http://retractionwatch.com/2017/08/25/co-author-now-retracted-paper-shooter-video-games-may-phd-revoked/

- *Read*: Diederich Stapels, http://www.nytimes.com/2013/04/28/magazine/diederik-stapels-audacious-academic-fraud.html?pagewanted=all

- *Read*: Wicherts et al., http://psycnet.apa.org/record/2006-12925-016


- *Read*: High Reliability Organizations https://ac.els-cdn.com/S1521689611000334/1-s2.0-S1521689611000334-main.pdf?_tid=ae5cb78c-c8cc-11e7-9e84-00000aacb35d&acdnat=1510616888_d35036482e58ef4f8990431da0b9c396

- *Write*: Each lab has practices that fall under the umbrella highly reliable organizations.  Write about how some of the practices in your lab meet the principles and how they do not.  500 words max.

Week 3.  **Preregistration and Open Science**  (JV)
There are many little decisions that people must make in performing research. These decisions are often made quickly, sometimes without much thought, and sometimes without awareness that a decision has been made.  To the extent that these little decisions tend to go in a preferred direction, they may be thought of as subtle biases.   Preregistration helps bring these decisions into the light where they may be critically examined.

Week 4. **Expanding The Document** (JV)
The traditional document has been thought of as output.  We find that sometimes people do not write what they do.  Here we stress the concept of a document as a process.  Documents are executed much like a program, and when they are, data are pulled, analyses are performed, graphs are drawn, tables are tabulated, and equations are typeset.  The process of all these things is encoded in the document.

Week 5. **Versioning: git push**. (JR)
Every lab encounters the clutter of having multiple, evolving versions of work products.  How do you deal with versioning?  We present different version strategies including the gold standard----git.

Week 6. **Working With Collaborators** (JV)
Working with collaborators is hard because they change our awesome text.  How do you work constructively, productively, and mistake free with people you dont want to talk to?

Week 7. **Basics Computer Skills: Linux/SQL/Python/Bash** (JV)
Computers don't make mistakes; people do.  So never ask a person to do a dumb, repetitive task when a computer can do it better!  This lecture is about working with scripts to automate tasks.  

Weeks 8-9. **Relational Databases**.  In these two weeks, we study perhaps the most useful technology for organizing a lab, relational databases. 

Week 10: **Hack a Lab!** (JR)

