---
title           : "Robustness of the subliminal cue effect: A planned preregistered meta-analysis"
shorttitle      : "subliminal cues - rubust or not (interrobang)"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Stephen Bennett
    affiliation : 1
  - name        : Gabriel Estrella
    affiliation : 1
  - name        : Mac Strelioff
    affiliation : 1
  - name        : Joachim Vandekerckhove
    affiliation : 1
  - name        : Jeffrey Rouder
    affiliation : 1
  

affiliation:
  - id          : 1
    institution : University of California, Irvine
    
output: prereg::cos_prereg
---

# Study Information

## Title

`r rmarkdown::metadata$title`

## Research questions

We aim to test whether the subliminal cue effect is robust to typical variation in experimental methods that might occur from labratory to labratory. Such variation typifies the sorts of generalizing to the real world. In general, is it the case that subliminal effects can substantively influence behavior?

It may be the case that these effects are restricted to some subset of the space of possible experimental methods. For instance, it may require a particular mask and cue contrast, mask duration, interval duration, and/or mask symbols. We aim to test the finding from (Reuss et al. 2015) that such an effect exists by thoroughly running through the space of all possible experiments.

## Experimental questions

Q1: When (i.e. under which covariates) does the masked cue increase or decrease response times in the target-clicking task?

Q2: When are masked cues are subliminal?

Q3: Is there a set of covariates for which subliminal cues impact target-clicking reaction time?

We will explore the various co-variates in the design and how they impact Q1 and Q2. In particular, we expect significant overlap between explicit (i.e. non-subliminal) cues and cues that impact reaction time in the target-clicking task.

## Data cleaning

Remove timings less then 250 milliseconds
Remove timings greater than 2,000 milliseconds
Take out the first trial of every block
Take out the first block

# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this section. Remember, all analyses specified in this section must be reported in the final article, and any additional analyses must be clearly labeled as exploratory or hypothesis generating in the final paper. A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis.

You may describe exploratory analyses in this section, but a clear confirmatory analysis is required. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

To help you keep track of multiple analyses, you may label each for your reference. -->

In order to assess whether a covariate impacts reaction times, we will compute Bayesian t-tests to observe if the data support the null or alternative hypothesis.

We intend to use the Bayes factor approach to assessing equalities and inequalities as described in Haaf & Rouder (in press) and Rouder & Haaf (submitted). 

The key specifications that are needed are the scale on effect sizes.  We think a guess for $\sigma^2$ is somewhere around .3, and if effects are .2, then effect sizes should be around .67.  This value will be used to set our scales along the arguments of Haaf and Rouder (in press).  

## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. -->

Defined above.

## Follow-up analyses
<!-- If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions. Refer to the *Hypotheses* section to relate each hypothesis to a statistical analysis. Remember that any analyses not specified in this research plan must be noted as exploratory. -->

We will fit an equal variance signal detection model to assess the applicability of a simple one-process model.

## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information you'll use (e.g. p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this? -->

Such considerations only make sense in the Neyman-Fisher statistical framework.  We don't make decisions .  Instead, we state the strength of evidence, and no criteria are needed.  See @Rouder:etal:2016c.

## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? -->

If the session is terminated (either by the participant or for technical reasons) the whole data set will be excluded. We have no set lower bound of performance, but we reserve the right to do exclude low-performing participants on an exploratory basis.  We do so with regards to the overall accuracy and explicitly not the accuracy-by-condition data.


## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent

# References
