---
title: The Mind of a Con Man
author: Yudhijit Bhattacharjee
date: April 26, 2013
---

# The Mind of a Con Man

One summer night in 2011, a tall, 40-something professor named Diederik Stapel stepped out of his elegant brick house in the Dutch city of Tilburg to visit a friend around the corner. It was close to midnight, but his colleague Marcel Zeelenberg had called and texted Stapel that evening to say that he wanted to see him about an urgent matter. The two had known each other since the early '90s, when they were Ph.D. students at the University of Amsterdam; now both were psychologists at Tilburg University. In 2010, Stapel became dean of the university's School of Social and Behavioral Sciences and Zeelenberg head of the social psychology department. Stapel and his wife, Marcelle, had supported Zeelenberg through a difficult divorce a few years earlier. As he approached Zeelenberg's door, Stapel wondered if his colleague was having problems with his new girlfriend.

Zeelenberg, a stocky man with a shaved head, led Stapel into his living room. "What's up?" Stapel asked, settling onto a couch. Two graduate students had made an accusation, Zeelenberg explained. His eyes began to fill with tears. "They suspect you have been committing research fraud."

Stapel was an academic star in the Netherlands and abroad, the author of several well-regarded studies on human attitudes and behavior. That spring, he published a widely publicized study in Science about an experiment done at the Utrecht train station showing that a trash-filled environment tended to bring out racist tendencies in individuals. And just days earlier, he received more media attention for a study indicating that eating meat made people selfish and less social.

His enemies were targeting him because of changes he initiated as dean, Stapel replied, quoting a Dutch proverb about high trees catching a lot of wind. When Zeelenberg challenged him with specifics --- to explain why certain facts and figures he reported in different studies appeared to be identical --- Stapel promised to be more careful in the future. As Zeelenberg pressed him, Stapel grew increasingly agitated.

Finally, Zeelenberg said: "I have to ask you if you're faking data."

"No, that's ridiculous," Stapel replied. "Of course not."

That weekend, Zeelenberg relayed the allegations to the university rector, a law professor named Philip Eijlander, who often played tennis with Stapel. After a brief meeting on Sunday, Eijlander invited Stapel to come by his house on Tuesday morning. Sitting in Eijlander's living room, Stapel mounted what Eijlander described to me as a spirited defense, highlighting his work as dean and characterizing his research methods as unusual. The conversation lasted about five hours. Then Eijlander politely escorted Stapel to the door but made it plain that he was not convinced of Stapel's innocence.

That same day, Stapel drove to the University of Groningen, nearly three hours away, where he was a professor from 2000 to 2006. The campus there was one of the places where he claimed to have collected experimental data for several of his studies; to defend himself, he would need details from the place. But when he arrived that afternoon, the school looked very different from the way he remembered it being five years earlier. Stapel started to despair when he realized that he didn't know what buildings had been around at the time of his study. Then he saw a structure that he recognized, a computer center. "That's where it happened," he said to himself; that's where he did his experiments with undergraduate volunteers. "This is going to work."

On his return trip to Tilburg, Stapel stopped at the train station in Utrecht. This was the site of his study linking racism to environmental untidiness, supposedly conducted during a strike by sanitation workers. In the experiment described in the Science paper, white volunteers were invited to fill out a questionnaire in a seat among a row of six chairs; the row was empty except for the first chair, which was taken by a black occupant or a white one. Stapel and his co-author claimed that white volunteers tended to sit farther away from the black person when the surrounding area was strewn with garbage. Now, looking around during rush hour, as people streamed on and off the platforms, Stapel could not find a location that matched the conditions described in his experiment.

"No, Diederik, this is ridiculous," he told himself at last. "You really need to give it up."

After he got home that night, he confessed to his wife. A week later, the university suspended him from his job and held a news conference to announce his fraud. It became the lead story in the Netherlands and would dominate headlines for months. Overnight, Stapel went from being a respected professor to perhaps the biggest con man in academic science.

I first met Stapel in the summer of 2012, nearly a year after his dismissal from Tilburg. I'd read about his fraud in various places, including the pages of Science magazine, where I work as a writer covering mostly astronomy and space science. Before seeing the news accounts, I was unaware of the study Stapel published in Science; the news writers there have no involvement with the research papers published in the magazine.

When Stapel and I met for lunch in Antwerp, about a 50-mile drive from Tilburg, investigating committees at the three universities where he had worked --- Amsterdam, Groningen and Tilburg --- were in the process of combing through his several dozen research papers to determine which ones were fraudulent. The scrutiny was meant not only to clean up the scientific record but also to establish whether any of Stapel's co-authors, including more than 20 Ph.D. students he supervised, shared any of the blame. It was already evident that many of the doctoral dissertations he oversaw were based on his fabricated data.

Right away Stapel expressed what sounded like heartfelt remorse for what he did to his students. "I have fallen from my throne --- I am on the floor," he said, waving at the ground. "I am in therapy every week. I hate myself." That afternoon and in later conversations, he referred to himself several times as tall, charming or handsome, less out of arrogance, it seemed, than what I took to be an anxious desire to focus on positive aspects of himself that were demonstrably not false.

Stapel's fraud may shine a spotlight on dishonesty in science, but scientific fraud is hardly new. The rogues' gallery of academic liars and cheats features scientific celebrities who have enjoyed similar prominence. The once-celebrated South Korean stem-cell researcher Hwang Woo Suk stunned scientists in his field a few years ago after it was discovered that almost all of the work for which he was known was fraudulent. The prominent Harvard evolutionary biologist Marc Hauser resigned in 2011 during an investigation by the Office of Research Integrity at the Department of Health and Human Services that would end up determining that some of his papers contained fabricated data.

Every year, the Office of Research Integrity uncovers numerous instances­ of bad behavior by scientists, ranging from lying on grant applications to using fake images in publications. A blog called Retraction Watch publishes a steady stream of posts about papers being retracted by journals because of allegations or evidence of misconduct.

Each case of research fraud that's uncovered triggers a similar response from scientists. First disbelief, then anger, then a tendency to dismiss the perpetrator as one rotten egg in an otherwise-honest enterprise. But the scientific misconduct that has come to light in recent years suggests at the very least that the number of bad actors in science isn't as insignificant as many would like to believe. And considered from a more cynical point of view, figures like Hwang and Hauser are not outliers so much as one end on a continuum of dishonest behaviors that extend from the cherry-picking of data to fit a chosen hypothesis --- which many researchers admit is commonplace --- to outright fabrication. Still, the nature and scale of Stapel's fraud sets him apart from most other cheating academics. "The extent to which I did it, the longevity of it, makes it extreme," he told me. "Because it is not one paper or 10 but many more."

Stapel did not deny that his deceit was driven by ambition. But it was more complicated than that, he told me. He insisted that he loved social psychology but had been frustrated by the messiness of experimental data, which rarely led to clear conclusions. His lifelong obsession with elegance and order, he said, led him to concoct sexy results that journals found attractive. "It was a quest for aesthetics, for beauty --- instead of the truth," he said. He described his behavior as an addiction that drove him to carry out acts of increasingly daring fraud, like a junkie seeking a bigger and better high.

When I asked Stapel if he had told me the truth, he looked offended. He didn't have any reason to lie anymore, he said. For more than a decade, he ran an experiment in deceit, and now he was finally ready for the truth --- to understand how and why he ended up in this place. "When you live your life and suddenly something extreme happens," he said, "your whole life becomes a bag of possible explanations for why you are here now."

Stapel lives in a picturesque tree-lined neighborhood in Tilburg, a quiet city of 200,000 in the south of the Netherlands. One afternoon last November, he sat in his kitchen eating a quickly assembled lunch of cheese, bread and chocolate sprinkles, running his fingers through his hair and mulling the future. The universities investigating him were preparing to come out with a final report a week later, which Stapel hoped would bring an end to the incessant flogging he had received in the Dutch media since the beginning of the scandal. The report's publication would also allow him to release a book he had written in Dutch titled "Ontsporing" --- "derailment" in English --- for which he was paid a modest advance. The book is an examination of his life based on a personal diary he started after his fraud was made public. Stapel wanted it to bring both redemption and profit, and he seemed not to have given much thought to whether it would help or hurt him in his narrower quest to seek forgiveness from the students and colleagues he duped.

Stapel brought out individually wrapped chocolate bars for us to share. As we ate them, I watched him neatly fold up his wrappers into perfectly rectangular shapes. Later, I got used to his reminding me not to leave doors ajar when we walked in or out of a room. When I pointed this out, he admitted to a lifelong obsession with order and symmetry.

Several times in our conversation, Stapel alluded to having a fuzzy, postmodernist relationship with the truth, which he agreed served as a convenient fog for his wrongdoings. "It's hard to know the truth," he said. "When somebody says, ‘I love you,' how do I know what it really means?" At the time, the Netherlands would soon be celebrating the arrival of St. Nicholas, and the younger of his two daughters sat down by the fireplace to sing a traditional Dutch song welcoming St. Nick. Stapel remarked to me that children her age, which was 10, knew that St. Nick wasn't really going to come down the chimney. "But they like to believe it anyway, because it assures them of presents," he told me with a wink.

In his early years of research --- when he supposedly collected real experimental data --- Stapel wrote papers laying out complicated and messy relationships between multiple variables. He soon realized that journal editors preferred simplicity. "They are actually telling you: ‘Leave out this stuff. Make it simpler,' " Stapel told me. Before long, he was striving to write elegant articles.

On a Sunday morning, as we drove to a village near Maastricht to see his parents, Stapel reflected on why his behavior had sparked such outrage in the Netherlands. "People think of scientists as monks in a monastery looking out for the truth," he said. "People have lost faith in the church, but they haven't lost faith in science. My behavior shows that science is not holy."

What the public didn't realize, he said, was that academic science, too, was becoming a business. "There are scarce resources, you need grants, you need money, there is competition," he said. "Normal people go to the edge to get that money. Science is of course about discovery, about digging to discover the truth. But it is also communication, persuasion, marketing. I am a salesman. I am on the road. People are on the road with their talk. With the same talk. It's like a circus." He named two psychologists he admired --- John Cacioppo and Daniel Gilbert --- neither of whom has been accused of fraud. "They give a talk in Berlin, two days later they give the same talk in Amsterdam, then they go to London. They are traveling salesmen selling their story."

The car let out a warning beep to indicate that we had exceeded the speed limit. Stapel slowed down. I asked him if he wished there had been some sort of alarm system for his career before it unraveled. "That would have been helpful, sure," he said. "I think I need shocks, though. This is not enough." Some friends, he said, asked him what could have made him stop. "I am not sure," he told me. "I don't think there was going to be an end. There was no stop button. My brain was stuck. It had to explode. This was the only way."

Stapel's father, Rob, who is in his 80s, walked out to greet us when we arrived. Stapel's mother, Dirkje, also in her mid-80s and a foot shorter than Stapel, made him tilt his head so that she could check out a rash on his forehead, which he said was due to stress. He gave them a copy of his book. His mother thumbed through the pages. "I never knew Diederik was so unhappy all these years," she told me, referring to the guilt and shame that Stapel described having lived with through his academic career.

Stapel was the youngest of four children. The family lived near Amsterdam, where Rob, a civil engineer, worked as a senior manager of the Schiphol Airport. Stapel told me that his father's devotion to his career led him to grow up thinking that individuals were defined by what they accomplished professionally. "That's what my parents' generation was like," he said. "You are what you achieve."

In high school, where Stapel says he excelled in his studies and at sports, he wrote and acted in plays. One of his friends was a student named Marcelle, a fellow actor who would later become his wife. After school, Stapel briefly studied acting at East Stroudsburg University in Pennsylvania before deciding his acting talents were mediocre and returning to the Netherlands to get an undergraduate degree in psychology.

He eventually applied to the University of Amsterdam to do a Ph.D. on how people judge others. He didn't get that slot --- it went to a young applicant from Leiden named Marcel Zeelenberg. But a year later, Stapel joined the university to pursue a doctorate on a different topic, assimilation and contrast, under a respected psychologist named Willem Koomen.

Assimilation and contrast are both established psychological effects. When people are primed with, or made to deliberate on, an abstract concept --- honesty, say, or arrogance --- they can be more likely to see it elsewhere. That's assimilation. Contrast can occur when people compare something to a concrete example, comparing themselves, for instance, to the image of a supermodel.

For his dissertation, Stapel did a series of experiments showing that whether people assimilate or contrast depends on context. In doing these studies, Stapel had to go through the tedium and messiness that are the essence of empirical science. To prime subjects, he designed word puzzles that, when solved, led his undergraduate volunteer subjects to words like "intelligence" or "Einstein." Then he asked them to read a story about a character and score the character on a numerical scale for intelligence, friendliness and other traits. Stapel found that when subjects were primed with something in the abstract, like the word "intelligence," they tended to find that trait more readily in themselves and in others, judging, for instance, a story character as more intelligent than they otherwise would have. Yet when they were primed with an example of the trait --- the word "Einstein" --- they tended to make a comparison, judging the story character as less intelligent.

Stapel got his Ph.D. in 1997. Koomen, who is still a professor at Amsterdam, does not doubt the integrity of Stapel's experiments for the doctorate. "Stapel was an extraordinarily gifted, enthusiastic and diligent Ph.D. student," Koomen told me via e-mail. "It was a privilege to work with him."

At Amsterdam, Stapel and Zeelenberg became close friends, working at two opposite corners on the same floor of the department. Zeelenberg was from a blue-collar family; Stapel came from a more privileged background. Unlike most graduate students, he wore suits on occasion. Zeelenberg recalls him as being obnoxious and cocky at times, but only because "he did know things better." He was also a "friendly, supportive warm guy," Zeelenberg said. When Stapel and Marcelle decided to marry in 1997, Zeelenberg attended Stapel's bachelor party on a boat ride along Amsterdam's canals.

Stapel stayed in Amsterdam for three years after his Ph.D., writing papers that he says got little attention. Nonetheless, his peers viewed him as having made a solid beginning as a researcher, and he won an award from the European Association of Experimental Social Psychology. In 2000, he became a professor at Groningen University.

While there, Stapel began testing the idea that priming could affect people without their being aware of it. He devised several experiments in which subjects sat in front of a computer screen on which a word or an image was flashed for one-tenth of a second --- making it difficult for the participants to register the images in their conscious minds. The subjects were then tested on a task to determine if the priming had an effect.

In one experiment conducted with undergraduates recruited from his class, Stapel asked subjects to rate their individual attractiveness after they were flashed an image of either an attractive female face or a very unattractive one. The hypothesis was that subjects exposed to the attractive image would --- through an automatic comparison --- rate themselves as less attractive than subjects exposed to the other image.

The experiment --- and others like it --- didn't give Stapel the desired results, he said. He had the choice of abandoning the work or redoing the experiment. But he had already spent a lot of time on the research and was convinced his hypothesis was valid. "I said --- you know what, I am going to create the data set," he told me.

Sitting at his kitchen table in Groningen, he began typing numbers into his laptop that would give him the outcome he wanted. He knew that the effect he was looking for had to be small in order to be believable; even the most successful psychology experiments rarely yield significant results. The math had to be done in reverse order: the individual attractiveness scores that subjects gave themselves on a 0-7 scale needed to be such that Stapel would get a small but significant difference in the average scores for each of the two conditions he was comparing. He made up individual scores like 4, 5, 3, 3 for subjects who were shown the attractive face. "I tried to make it random, which of course was very hard to do," Stapel told me.

Doing the analysis, Stapel at first ended up getting a bigger difference between the two conditions than was ideal. He went back and tweaked the numbers again. It took a few hours of trial and error, spread out over a few days, to get the data just right.

He said he felt both terrible and relieved. The results were published in The Journal of Personality and Social Psychology in 2004. "I realized --- hey, we can do this," he told me.

Stapel's career took off. He published more than two dozen studies while at Groningen, many of them written with his doctoral students. They don't appear to have questioned why their supervisor was running many of the experiments for them. Nor did his colleagues inquire about this unusual practice.

In 2006, Stapel moved to Tilburg, joining Zeelenberg. Students flocked to his lab, and he quickly rose in influence. In September 2010, he became dean of the School of Social and Behavioral Sciences. He could have retreated from active research to focus on administration, but, he told me, he couldn't resist the allure of fabricating new results. He had already made up the data for the Utrecht train-station study and was working on the paper that would appear in Science the following year. Colleagues sought him out to take part in new collaborations.

Stapel designed one such study to test whether individuals are inclined to consume more when primed with the idea of capitalism. He and his research partner developed a questionnaire that subjects would have to fill out under two subtly different conditions. In one, an M&M-filled mug with the word "kapitalisme" printed on it would sit on the table in front of the subject; in the other, the mug's word would be different, a jumble of the letters in "kapitalisme." Although the questionnaire included questions relating to capitalism and consumption, like whether big cars are preferable to small ones, the study's key measure was the amount of M&M's eaten by the subject while answering these questions. (The experimental approach wasn't novel; similar M&M studies had been done by others.) Stapel and his colleague hypothesized that subjects facing a mug printed with "kapitalisme" would end up eating more M&M's.

Stapel had a student arrange to get the mugs and M&M's and later load them into his car along with a box of questionnaires. He then drove off, saying he was going to run the study at a high school in Rotterdam where a friend worked as a teacher.

Stapel dumped most of the questionnaires into a trash bin outside campus. At home, using his own scale, he weighed a mug filled with M&M's and sat down to simulate the experiment. While filling out the questionnaire, he ate the M&M's at what he believed was a reasonable rate and then weighed the mug again to estimate the amount a subject could be expected to eat. He built the rest of the data set around that number. He told me he gave away some of the M&M stash and ate a lot of it himself. "I was the only subject in these studies," he said.

Around the same time that Stapel was planning this study --- which would not end up being published --- he was approached by another colleague of his at Tilburg, Ad Vingerhoets, who asked Stapel to help him design a study to understand whether exposure to someone crying affects empathy. Stapel came up with what Vingerhoets told me was an "excellent idea." They would give elementary-school children a coloring task in which half the kids would be asked to color an inexpressive cartoon character, while the other half would have to color the same character shown shedding a tear. Upon completing the task, the children would receive candy and then be asked if they were willing to share the candy with other children --- a measure of pro-social behavior.

Stapel and Vingerhoets worked together with a research assistant to prepare the coloring pages and the questionnaires. Stapel told Vingerhoets that he would collect the data from a school where he had contacts. A few weeks later, he called Vingerhoets to his office and showed him the results, scribbled on a sheet of paper. Vingerhoets was delighted to see a significant difference between the two conditions, indicating that children exposed to a teary-eyed picture were much more willing to share candy. It was sure to result in a high-profile publication. "I said, ‘This is so fantastic, so incredible,' " Vingerhoets told me.

He began writing the paper, but then he wondered if the data had shown any difference between girls and boys. "What about gender differences?" he asked Stapel, requesting to see the data. Stapel told him the data hadn't been entered into a computer yet.

Vingerhoets was stumped. Stapel had shown him means and standard deviations and even a statistical index attesting to the reliability of the questionnaire, which would have seemed to require a computer to produce. Vingerhoets wondered if Stapel, as dean, was somehow testing him. Suspecting fraud, he consulted a retired professor to figure out what to do. "Do you really believe that someone with [Stapel's] status faked data?" the professor asked him.

"At that moment," Vingerhoets told me, "I decided that I would not report it to the rector."

If Stapel's status served as a shield, his confidence fortified him further. His presentations at conferences were slick and peppered with humor. He viewed himself as giving his audience what they craved: "structure, simplicity, a beautiful story." Stapel glossed over experimental details, projecting the air of a thinker who has no patience for methods. The tone of his talks, he said, was "Let's not talk about the plumbing, the nuts and bolts --- that's for plumbers, for statisticians." If somebody asked a question --- on the possible effect of changing a condition in the experiment, for example --- he made things up on the spot. "I would often say, ‘Well, I have thought about this, we did another experiment which I haven't reported here in which we tried that and it didn't work.' "

And yet as part of a graduate seminar he taught on research ethics, Stapel would ask his students to dig back into their own research and look for things that might have been unethical. "They got back with terrible lapses­," he told me. "No informed consent, no debriefing of subjects, then of course in data analysis, looking only at some data and not all the data." He didn't see the same problems in his own work, he said, because there were no real data to contend with.

Rumors of fraud trailed Stapel from Groningen to Tilburg, but none raised enough suspicion to prompt investigation. Stapel's atypical practice of collecting data for his graduate students wasn't questioned, either. Then, in the spring of 2010, a graduate student noticed anomalies in three experiments Stapel had run for him. When asked for the raw data, Stapel initially said he no longer had it. Later that year, shortly after Stapel became dean, the student mentioned his concerns to a young professor at the university gym. Each of them spoke to me but requested anonymity because they worried their careers would be damaged if they were identified.

The professor, who had been hired recently, began attending Stapel's lab meetings. He was struck by how great the data looked, no matter the experiment. "I don't know that I ever saw that a study failed, which is highly unusual," he told me. "Even the best people, in my experience, have studies that fail constantly. Usually, half don't work."

The professor approached Stapel to team up on a research project, with the intent of getting a closer look at how he worked. "I wanted to kind of play around with one of these amazing data sets," he told me. The two of them designed studies to test the premise that reminding people of the financial crisis makes them more likely to act generously.

In early February, Stapel claimed he had run the studies. "Everything worked really well," the professor told me wryly. Stapel claimed there was a statistical relationship between awareness of the financial crisis and generosity. But when the professor looked at the data, he discovered inconsistencies confirming his suspicions that Stapel was engaging in fraud.

The professor consulted a senior colleague in the United States, who told him he shouldn't feel any obligation to report the matter. But the person who alerted the young professor, along with another graduate student, refused to let it go. That spring, the other graduate student examined a number of data sets that Stapel had supplied to students and postdocs in recent years, many of which led to papers and dissertations. She found a host of anomalies, the smoking gun being a data set in which Stapel appeared to have done a copy-paste job, leaving two rows of data nearly identical to each other.

The two students decided to report the charges to the department head, Marcel Zeelenberg. But they worried that Zeelenberg, Stapel's friend, might come to his defense. To sound him out, one of the students made up a scenario about a professor who committed academic fraud, and asked Zeelenberg what he thought about the situation, without telling him it was hypothetical. "They should hang him from the highest tree" if the allegations were true, was Zeelenberg's response, according to the student.

The students waited till the end of summer, when they would be at a conference with Zeelenberg in London. "We decided we should tell Marcel at the conference so that he couldn't storm out and go to Diederik right away," one of the students told me.

In London, the students met with Zeelenberg after dinner in the dorm where they were staying. As the night wore on, his initial skepticism turned into shock. It was nearly 3 when Zeelenberg finished his last beer and walked back to his room in a daze. In Tilburg that weekend, he confronted Stapel.

After his visit to the Utrecht train station on the day he was questioned by the rector, Stapel got home around midnight. His wife, Marcelle, was waiting for him in the living room, but he didn't tell the whole truth until the next day. "Eight or 10 years of my life suddenly had another color," Marcelle told me one evening in November, when Stapel left us alone to talk.

The following week, as university officials were preparing to make the charges public, the couple sat down to explain matters to their daughters. "Are you going to die?" the girls asked, followed by questions about two other issues fundamental to their lives: "Are you getting divorced?" "Are we going to move?" "No," Marcelle answered. The girls were relieved. "Well, Daddy," their younger daughter said. "You always say that you can make mistakes, but you have to learn from it."

Marcelle described to me how she placed Stapel inside an integrity scanner in her mind. "I sort of scanned his life in terms of being a father, being my husband, being my best friend, being the son of his parents, the friend of his friends, being a human being that is part of society, being a neighbor --- and being a scientist and teacher," she told me. "Then I found out for myself that all of these other parts were really O.K. I thought --- Wow, it must be Diederik and science which is a poisoned combination."

Nonetheless, she experienced waves of anger. She was furious thinking about the nights when Stapel wouldn't come to bed because he was working on his research. "I said, ‘It's for science,' " she told me. "But it's not." She struggled to understand why he had plied his students with fake data. She explained it to herself as a twisted effort by Stapel to give his students a perfect research life, similar to the one he built for himself. In doing so, of course, "he made their worlds really unhappy and imperfect," she said.

In late October, nearly two months after the scandal broke, the university issued an interim report portraying Stapel as an arrogant bully who cozied up to students in order to manipulate them. Stapel broke down after reading the personality assessment. "He was calling for his mother, he was freaking out," Marcelle told me. "He was trying to get out of the window." Stapel's psychiatrist prescribed extra medication, and a friend made him promise Marcelle that he would not kill himself. To escape the media's glare, he went to spend a few days with his brother in Budapest.

Back in Tilburg, Stapel sank into a deep depression. Through the winter he filled a series of Moleskine diaries with reflections on his life. It was an accounting exercise encouraged by his therapist. Forgiven by his wife, Stapel wondered if he would ever be forgiven by those he had damaged the most --- his students and postdocs.

A few reached out. One day in December 2011, Saskia Schwinghammer, a former student and now a researcher at the University of Applied Sciences in Utrecht, visited him at his home. Stapel wept as he apologized. He reminded her that she and other students were in no way to blame, that they did not have to feel they should have been more discerning when accepting data from him. "You came up with these ideas," Stapel told her. "You designed the studies. I took away one little thing from the process. Don't let people think that you're worthless because you worked with me."

Schwinghammer left teary-eyed. "It was good to have seen you," she said. A year later, she told me she had forgiven the man but not his actions. "There are good people doing bad things," she said, "there are bad people doing good things." She put Stapel in the former category.

At the end of November, the universities unveiled their final report at a joint news conference: Stapel had committed fraud in at least 55 of his papers, as well as in 10 Ph.D. dissertations written by his students. The students were not culpable, even though their work was now tarnished. The field of psychology was indicted, too, with a finding that Stapel's fraud went undetected for so long because of "a general culture of careless, selective and uncritical handling of research and data." If Stapel was solely to blame for making stuff up, the report stated, his peers, journal editors and reviewers of the field's top journals were to blame for letting him get away with it. The committees identified several practices as "sloppy science" --- misuse of statistics, ignoring of data that do not conform to a desired hypothesis and the pursuit of a compelling story no matter how scientifically unsupported it may be.

The adjective "sloppy" seems charitable. Several psychologists I spoke to admitted that each of these more common practices was as deliberate as any of Stapel's wholesale fabrications. Each was a choice made by the scientist every time he or she came to a fork in the road of experimental research --- one way pointing to the truth, however dull and unsatisfying, and the other beckoning the researcher toward a rosier and more notable result that could be patently false or only partly true. What may be most troubling about the research culture the committees describe in their report are the plentiful opportunities and incentives for fraud. "The cookie jar was on the table without a lid" is how Stapel put it to me once. Those who suspect a colleague of fraud may be inclined to keep mum because of the potential costs of whistle-blowing.

The key to why Stapel got away with his fabrications for so long lies in his keen understanding of the sociology of his field. "I didn't do strange stuff, I never said let's do an experiment to show that the earth is flat," he said. "I always checked --- this may be by a cunning manipulative mind --- that the experiment was reasonable, that it followed from the research that had come before, that it was just this extra step that everybody was waiting for." He always read the research literature extensively to generate his hypotheses. "So that it was believable and could be argued that this was the only logical thing you would find," he said. "Everybody wants you to be novel and creative, but you also need to be truthful and likely. You need to be able to say that this is completely new and exciting, but it's very likely given what we know so far."

Fraud like Stapel's --- brazen and careless in hindsight --- might represent a lesser threat to the integrity of science than the massaging of data and selective reporting of experiments. The young professor who backed the two student whistle-blowers told me that tweaking results --- like stopping data collection once the results confirm a hypothesis --- is a common practice. "I could certainly see that if you do it in more subtle ways, it's more difficult to detect," Ap Dijksterhuis, one of the Netherlands' best known psychologists, told me. He added that the field was making a sustained effort to remedy the problems that have been brought to light by Stapel's fraud.

When Stapel's book came out, it got a mixed reception from critics, and it angered many in the Netherlands who thought it dishonorable of him to try to profit from his misdeeds. Within days of its release, the book appeared online in the form of PDFs, posted by those who wanted to damage his chances of making money. Unlike Schwinghammer and a few others, most of his former students have not responded to his apologies. Late last year, the Dutch government said it was investigating whether Stapel misused public funds in the form of research grants.

I asked Zeelenberg how he felt toward Stapel a year and a half after reporting him to the rector. He told me that he found himself wanting to take a longer route to the grocery store to avoid walking past Stapel's house, lest he run into him. "When this is all over, I would like to talk to him," Zeelenberg said. "Then I'll find out if he and I are capable of having a friendship. I miss him, but there are equal amounts of instances when I want to punch him in the face."

The unspooling of Stapel's career has given him what he managed to avoid for much of his life: the experience of failure. On our visit to Stapel's parents, I watched his discomfort as Rob and Dirkje tried to defend him. "I blame the system," his father said, steadfast. His argument was that Stapel's university managers and journal editors should have been watching him more closely.

Stapel shook his head. "Accept that this happened," he said. He seemed to be talking as much to himself as to his parents. "You cannot say it is because of the system. It is what it is, and you need to accept it." When Rob and Dirkje kept up their defense, he gave them a weak smile. "You are trying to make the pain go away by saying this is not part of me," he said. "But what we need to learn is that this happened. I did it. There were many circumstantial things, but I did it."